variables:
#    TEMPLATE_DISABLE: "1"
    TEMPLATE_DEB_NAME: "unipi-kernel-modules"

include: 
    project: docker/template
    file: debian-pkg.yaml

##############################################################
# build on schedule or trigger 
# check kernel versions and trigger to generate last tagged version

check-master-schedule:
    tags: ['amd64']
    only:
        - triggers
        - schedules
    script:
        - bash kernels_check.sh

