
##############################################################
# build on schedule or trigger 
# check kernel versions and trigger to generate last tagged version

check-master-schedule:
    tags: ['amd64']
    only:
        - triggers
        - schedules
    script:
        - bash kernels_check.sh

