variables:
#    TEMPLATE_DISABLE: "1"
    TEMPLATE_DEB_NAME: "unipi-kernel-modules"

include: 
    project: docker/template
    file: debian-pkg.yaml

##############################################################
build-newstable:nano:
    extends: .build_for_newstable
    tags: ['arm64']
    before_script: 
        - apt-get update
        - apt-get install -y axon-kernel-headers

build-newstable:rpi:
    extends: .build_for_newstable
    tags: ['armhf']

build-newstable:all:
    extends: .build_for_newstable
    tags: ['amd64']

build-stable:nano:
    extends: .build_for_stable
    tags: ['arm64']
    before_script: 
        - apt-get update
        - apt-get install -y axon-kernel-headers

build-stable:rpi:
    extends: .build_for_stable
    tags: ['armhf']

build-stable:all:
    extends: .build_for_stable
    tags: ['amd64']


build-oldstable:nano:
    extends: .build_for_oldstable
    tags: ['arm64']
    before_script: 
        - apt-get update
        - apt-get install -y axon-kernel-headers

build-oldstable:rpi:
    extends: .build_for_oldstable
    tags: ['armhf']

build-oldstable:all:
    extends: .build_for_oldstable
    tags: ['amd64']


deploy-test:
    extends: .deploy_test

deploy-release:
    extends: .deploy_master

# build on schedule or trigger 
# for autogenerated package on raspbian version depended
.build-stable-schedule:nano:
    extends: .build_for_stable
    tags: ['arm64']
    only:
        - triggers
        - schedules
    script:
        - bash .axoncheck_and_gen.sh unipi-kernel-modules

.build-stable-schedule:rpi:
    extends: .build_for_stable
    tags: ['armhf']
    only:
        - triggers
        - schedules
    script:
        - bash .rpicheck_and_gen.sh unipi-kernel-modules

build-oldstable-schedule:nano:
    extends: .build_for_oldstable
    tags: ['arm64']
    only:
        - triggers
        - schedules
    script:
        - bash .axoncheck_and_gen.sh unipi-kernel-modules

.build-oldstable-schedule:rpi:
    extends: .build_for_oldstable
    tags: ['armhf']
    only:
        - triggers
        - schedules
    script:
        - bash .rpicheck_and_gen.sh unipi-kernel-modules

